watches:
  - repo: "upscopeio/ios-sdk"
    workflows:
      - "ci.yml"
      - "test-apps.yml"
      - "publish.yml"
  - repo: "upscopeio/upscope"
    workflows:
      - "ci-api.yml"
      - "ci-data.yml"
      - "ci-e2e.yml"
      - "ci-lint-typecheck.yml"
      - "deploy-app-staging.yml"
      - "deploy-app-production.yml"
      - "deploy-data-onprem.yml"
      - "deploy-data-staging.yml"
      - "deploy-data-production.yml"
      - "deploy-js-staging.yml"
      - "deploy-js-production.yml"
      - "create-production-pr.yml"
  - repo: "upscopeio/android-sdk"
    workflows:
      - "ci.yml"
      - "test-apps.yml"
      - "publish.yml"
  - repo: "upscopeio/react-native-sdk"
    workflows:
      - "test-apps.yml"
      - "publish.yml"
  - repo: "upscopeio/react-native-sdk"
    workflows:
      - "test-apps.yml"
      - "publish.yml"
